### ISSUE TITLE
Add back gprof

### ISSUE THREAD

**Issue by ducalex** [skeeto/w64devkit#109]
In commit c6ae17490043e82cd8c9ef68e8e1a67701a0eeaf gprof was removed. However, gprof can still work if the program is compiled with `-pg -no-pie`. So I think it should be added back because it's useful if one knows about that caveat!

**Comment by skeeto** [comment]
I removed it because it didn't work between w64devkit 1.6.0 and 1.13.0 
even with -no-pie. PIE effectively became mandatory in Binutils 2.36 and 
-no-pie did nothing. GCC 12 makes PIE optional again, but I hadn't noticed 
the change.

***@***.***/msg267070.html

I just restored gprof in 6708972b and confirmed that it works normally.
