### ISSUE TITLE
does w64devkit include a regex header/lib ? With C.

### ISSUE THREAD

**Issue by ggbbrr** [skeeto/w64devkit#127]
I'm trying to compile a C program with regex. I get "fatal error: regex.h: No such file or directory".

**Comment by skeeto** [comment]
That's a POSIX API:
https://pubs.opengroup.org/onlinepubs/7908799/xsh/regex.h.html

w64devkit is for native Windows development, so it doesn't have POSIX 
compatibility beyond a few small odds and ends in Mingw-w64. You'll need 
to find, or write, a POSIX regex implementation which supports Windows.

PCRE includes a "pcre2posix" library implementing the POSIX API. I built 
it from source in w64devkit just now, and it wasn't terribly difficult to 
get up and running. I wrote a "regex.h" with one line:

#include <pcre2posix.h>

After which POSIX regex.h sample programs worked without changes. Caveat: 
if you're using the static library (default build), use --static with 
pkg-config so that it picks up libpcre2-8:

    pkg-config --static --libs libpcre2-posix

Otherwise be sure to link libpcre2-8 last, because order matters.

A more laborious option is to wrap the regex engine in libstdc++, included 
in w64devkit, to present the C POSIX API, even if with with some regex 
incompatibilities.

https://en.cppreference.com/w/cpp/regex

(That could be an interesting project on its own.)

**Comment by skeeto** [comment]
Since it sounded like an interesting challenge, I just added a custom PCRE 
build to contrib/ that provides a POSIX regex library, and only that exact 
functionality, via the POSIX names and regex.h. You can't even tell it's 
PCRE behind the scenes. None of this will be distributed in w64devkit, and 
it's still up to you to build+install the library via the script.

This is the second such that I've made, and I'm planning to collect more 
in contrib/ in the future.

**Comment by skeeto** [comment]
Thanks for the tip, @avih. I didn't know about this library. The generated 
header stuff is unfortunate, but the librxspencer fork addresses that, as 
well as general cleanup. If I were going to use or distribute it, I'd make 
a few more, small tweaks (fix the to{lower,upper} UB, change strcpy into 
memcpy, include guard in regex2.h, delete some unnecessary code, and a 
unity build), but that's probably it. Good find!

> Not sure if you mean more libraries in general

The other one is a garbage collector, libgc.c (a stripped down Boehm GC), 
so in general. Were I to use these libraries in a serious project, here's 
how I'd handle them, depending on the subset of features I want to use. If 
I take time to figure it out, I can capture it in contrib/.

There's another in 6f1f2b9b with Expat, where I'm considering skipping its 
build system when building w64devkit. The complete library is a mere three 
translation units, so a 25KLOC build system — substantially more code than 
the library itself — is rather silly, especially since most of it is waste 
(checking if size_t is defined, etc.). I'm even tempted to amalgamate it 
and include it in this repository, making it one less dependency to fetch, 
though that complicates the repository's licensing.

There's yet another here, though not exactly a library, substantial enough 
to warrant its own repository. It builds and installs an "f77" compiler 
without needing gfortran:

https://github.com/skeeto/f2c-w64devkit

My philosophy is that binary distributions should have ownership of their 
dependencies, either directly or through contract. If a dependency has an 
issue that requires attention, it must be possible to fix without waiting 
for unpaid, upstream volunteers to do it. Language-based package managers 
have no hooks to patch packages, placing you at the mercy of the upstream 
internet randos that maintain it. Linux distributions mostly have it right 
*for themselves*, where they start from an upstream source artifact, then 
maintain a local patchset on top, a kind of light fork, that integrates it 
into the distribution, independent of the upstream project.

That's why I'm uninterested in distributing libraries in w64devkit, aside 
from the essential toolchain runtime bits. (IMHO, Mingw-w64 goes too far 
when it includes POSIX functionality not in MSVCRT, but I'm not going to 
rip that out.) That even includes POSIX regular expressions.

**Comment by avih** [comment]
> That's why I'm uninterested in distributing libraries in w64devkit, aside from the essential toolchain runtime bits.

Yeah, I don't disagree.

Specifically about regex though, since you already have a PCRE based thingy, I thought you might be interested in something much smaller which provides possibly good enough functionality.

I think I'll use it (the spencer one) if I need regex, though TBH I don't need it often or really at all, but having a small windows-compatible POSIX regex lib is just too good to ignore IMHO.

FWIW, tcl used (uses?) an earlier version of the spencer V8 regex code as its regex engine, and so does `less` as fallback when system regex is unavailable - e.g. on Windows, though I've not yet seen projects which vendor the spencer BSD POSIX code, and I've always wanted to have POSIX regex API for windows...

**Comment by avih** [comment]
Off topic for this thread, but in general, autoconf (and I guess libtool) would be nice to have, especially to build from a git repo rather than a source tarball, but I don't know enough on autotools to begin with (other than using it to generate `configure`).

**Comment by stianhoiland** [comment]
I'm somehow messing up when trying to use this regex solution. I downloaded a PCRE2 v10.45 release from [here](https://github.com/PCRE2Project/pcre2/releases), and tried to `./configure && make -j8` which worked fine. Then downloaded your `libregex.c` script in `contrib`, copied it to the `pcre2-10.45` folder and ran it. It finished successfully. `find . -mtime -1`:
```sh
./x86_64-w64-mingw32/include
./x86_64-w64-mingw32/include/regex.h
./x86_64-w64-mingw32/lib
./x86_64-w64-mingw32/lib/libregex.a
```
In the program I'm trying to build I added `-lregex` to `LDLIBS`, but when I `make` I get this:
```sh
cc   -o er er.o -lm -lregex
C:/Users/stian/Downloads/w64devkit-x64/bin/ld.exe: C:/Users/stian/Downloads/w64devkit-x64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libregex.a(libregex.o):libregex.c:(.text+0x6f9e): undefined reference to `_pcre2_compile_class_nested_8'
C:/Users/stian/Downloads/w64devkit-x64/bin/ld.exe: C:/Users/stian/Downloads/w64devkit-x64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libregex.a(libregex.o):libregex.c:(.text+0x72f1): undefined reference to `_pcre2_compile_class_not_nested_8'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:14: er] Error 1
```
Got any clues for me?

**Comment by Peter0x44** [comment]
Here is the line of libregex.c that creates the lib
> ${AR:-ar} -r "$PREFIX/lib/libregex.a" libregex.o
it only contains libregex.o, which depends on PCRE. So you need to link PCRE along with libregex.

**Comment by skeeto** [comment]
The intention is that `libregex.a` is enough on its own, because the contrib script doesn't install anything else, and so you can pretend PCRE isn't involved. I notice from your output you're using an older w64dk (includes the arch triple in the sysroot), but that should be fine.

Your problem is using PCRE2 10.45 instead of version 10.43 as indicated in `libregex.c`. Despite the small version bump, 10.45 was a major overhaul of the library with ~200k changes, and so `libregex.c` would need to be reworked to support it. There's nothing relevant in 10.45 for POSIX regex, so using the older version makes no difference.

**Comment by stianhoiland** [comment]
@Peter0x44 Thanks for the suggestion. I also thought maybe it could be that.

@skeeto wrote:

> The intention is that libregex.a is enough on its own, because the contrib script doesn't install anything else, and so you can pretend PCRE isn't involved.

This was the impression I got from your instructions, but I was unsure when I couldn't get it to work.

I saw the bigness of the PCRE2 10.45 update, but thought it would either just work with your script or else it would be worth hashing out in a discussion here. Thanks for confirming. I tried 10.44 and it at least compiles without the errors above. (I haven't gotten around to testing it at runtime yet.)

> I notice from your output you're using an older w64dk (includes the arch triple in the sysroot), but that should be fine.

It's barely been 3 weeks! "Old"! :)
