### ISSUE TITLE
Access to D: drive (secondary drive) denied on windows

### ISSUE THREAD

**Issue by YaserAlOsh** [skeeto/w64devkit#139]
Hello,

I am facing an issue with the fortran w64devkit .exe. I am running it on windows 10, and inside the terminal I try to access the d: drive, because that's where my projects are located, but I always get a permission denied error. I have tried running in administrator mode, and running from inside an admin cmd (sh -l). Both methods didn't work.

![image](https://github.com/skeeto/w64devkit/assets/25433731/b335ba09-d738-4da1-8c14-ec39bc5151df)

Would appreciate help in solving this.
Thanks in advance.

**Comment by grable0** [comment]
Have you tried `cd D:/` ?

**Comment by skeeto** [comment]
The w64devkit shell is busybox-w32 ash, a POSIX shell, which behaves 
differently than cmd.exe. To change drives, "cd d:" just like you would 
any other directory change. Changing the current drive isn't a special 
case operation. When you type "d:" you're (I think) telling the shell to 
execute the drive like a program. Since you can't execute a drive, it 
fails with the error translated to a permission error.

**Comment by YaserAlOsh** [comment]
Oh, it worked. Silly mistake.
Thanks a lot!
________________________________

**Comment by rmyorston** [comment]
>When you type "d:" you're (I think) telling the shell to execute the drive like a program.

Actually, `D:` refers to the _current directory_ of drive D. If you haven't visited D before it'll be the top-level directory of the drive (`D:/`). The effect is much the same: you can't execute a directory so the command fails.

Paths of the form `D:path` (note, no slash after the colon) are _relative_ to the current directory of the drive.

For more about this and how busybox-w32 handles paths see my [pathnames](https://frippery.org/busybox/paths.html) webpage.

**Comment by skeeto** [comment]
Thanks for the info, Ron. I didn't know some of this, and it's very 
helpful!
