### ISSUE TITLE
Using UTF-8 code page

### ISSUE THREAD

**Issue by averms** [skeeto/w64devkit#15]
In cmd.exe one can use `chcp 65001` to temporarily change the code page to utf-8. This doesn't seem to work in w64devkit.exe. Running `chcp 65001` inside cmd.exe and then starting `busybox sh -l` doesn't work either. Is it possible to make this work?

**Comment by skeeto** [comment]
Unfortunately standard C functions in the C runtime on Windows only hook 
up to the "ANSI" Windows API, and busybox-w32 makes practically no effort 
to route around it (via proprietary Windows functionality) in order to use 
the Unicode API. As result, it's stuck with CP-1252 for now regardless of 
the console's code page. Everything is quietly mangled to CP-1252 before 
BusyBox even sees it, which is why changing the console code page doesn't 
help. So unfortunately I don't think there's anything you can do.

However, I just recently learned of a new trick that allows Win32 programs 
to speak some UTF-8 without source modification. To enable, applications 
include some ugly XML as a resource manifest, which covers command line 
arguments (argv) and standard functions accepting paths (e.g. fopen). 
Setting the console code page to UTF-8 even allows it to correctly output 
UTF-8 to the console. It still doesn't work with console input, and I have 
no idea why not.

https://docs.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page
https://stackoverflow.com/questions/20255591/manifest-being-ignored-in-mingw-app

I'd like to start building busybox-w32 with this manifest, Though that 
still doesn't solve the UTF-8 input problem.

**Comment by skeeto** [comment]
I read more documentation, had an insight, tried it out, and I have some 
slightly better news. If you save that XML manifest from my first link to 
a file called "busybox.exe.manifest", then place it next to busybox.exe, 
you'll get partial Unicode support from BusyBox. It correctly receives and 
passes UTF-8 arguments, and can access Unicode paths and file names. (My 
BusyBox command aliases all use the Unicode API, and so don't individually 
require manifests.)

Note: This manifest is called a "side-by-side assembly", and Windows 
caches them (WinSxS). You may need to "touch" busybox.exe so that it 
resets the cache and recognizes the manifest.

However, two issues remain:

* As mentioned previously, Windows doesn't support UTF-8 input despite 
everything saying it should. SetConsoleCP() returns success, and it 
reports that it's using UTF-8, but the input is still silently mangled 
just as it's always been. As far as I can tell, this is a bug in Windows, 
and hopefully something they'll get to fixing this decade.

* BusyBox's line editing is confused by mutlibyte characters and gets 
into a bad state when manipulating commands containing them. I couldn't 
just type these into BusyBox of course, but I was able to sneak some in by 
way of the history file. This is an issue unique to busybox-w32 since 
upstream BusyBox correctly handles multibyte characters.

These two issues are disruptive enough that I don't think it's worth 
embedding the UTF-8 manifest into BusyBox at this time, but at least you 
can easily apply a manifest yourself.

**Comment by averms** [comment]
Wow, thank you for pointing me to this XML code page stuff. I read your blog post and it sounds very promising.
I'll close this for now.
