### ISSUE TITLE
ld.exe: cannot find -lgcc_eh: No such file or directory

### ISSUE THREAD

**Issue by ZCShou** [skeeto/w64devkit#152]
The other MinGW-w64 release have a libgcc_eh.a in lib folder but w64devkit has no it.

**Comment by skeeto** [comment]
I only enable static libstdc++, so libgcc_eh is rolled into libgcc. If a 
build system uses -lgcc_eh then it's probably unaware libstdc++ is being 
statically linked and you should request a static build. If it still tries 
to link libgcc_eh in a static build, then the build is subtly broken and 
you'll need to find some way to override the "LDLIBS" flags.

Static libstdc++ is not without cost, though the costs are undocumented by 
GCC, and doubly so on Windows where dynamic linking fundamentally differs 
from ELF. An obvious cost is that every module (DLL, EXE) contains a copy 
of at least part of libstdc++, typically ~100k to ~1M depending on what 
you're using. (Don't forget that when it comes to license compliance.)

A less obvious cost is that sharing standard library objects across module 
boundaries is unsupported — e.g. passing a std::string through an exported 
function. Or at least that's my understanding. Unlike on Linux, on Windows 
it's perfectly sound to have multiple, incompatible libstdc++ linked into 
a single process. Modules will link to the correct functions even if they 
have a common name (e.g. operator new). But if you share standard library 
objects, even between DLLs statically linked with the same libstdc++, the 
receiver will use its own copy of these functions on the objects. In most 
cases this is harmless, but in a few cases it won't work correctly, such 
as when there are global variables involved. They each use their own copy 
of these variables. One such instance is winpthreads (which, to be honest, 
is not implemented so well), affecting all threading objects.

The prohibition on sharing standard library objects extends (with lower 
confidence on my part) to throwing exceptions across module boundaries, 
which is why you don't need libgcc_eh when static linking libstdc++. I 
could potentially supply an empty, dummy libgcc_eh — like Mingw-w64 does 
with -lm — to smooth over linking hiccups, but that would cover up subtle 
compatibility problems. If a build wants to use -lgcc_eh in w64dk, that's 
a sign something may be wrong with the build.

Why only supply static libstdc++? For simplicity in the typical case, and 
especially because dynamic libstdc++ is less useful on Windows, which has 
no common, system C++ standard library. There's no C++ ABI compatibility 
except within a project where all modules are compiled together at the 
same time. Instead the official solution to this problem is COM.

Note: C++ prohibitions are strictly about libstd++ objects, and (again, 
lower confidence) maybe exceptions. You can still use the C++ ABI across 
DLL boundaries, without extern C, within a project so long as it does not 
expose libstdc++ objects. That's trivial if you do not link libstdc++, for 
instance. Though in practice, for typical C++, this doesn't mean much.

**Comment by ZCShou** [comment]
Thanks for your reply. I use w64devkit for rust with gnu toolchain on Windows. When I run cargo build, It display an error ld.exe: cannot find -lgcc_eh: No such file or directory.

According to your reply  I know the reason,thanks!

**Comment by Peter0x44** [comment]
I believe #52 covers your same issue with rust. This is a dup of that.

**Comment by ZCShou** [comment]
Yes. Thanks!
