### ISSUE TITLE
Windows Security and False Positive for Release v2.0.0

### ISSUE THREAD

**Issue by gpadd** [skeeto/w64devkit#158]
I've gotten false-positives for just opening the file, Windows Security wants to delete the executable (w64devkit-x64-2.0.0.exe) so I had to explicitly allow it in Windows Virus & Threat protection.

My hunch is that Windows Security don't like the automatic unzipping of the file.

Solution could be to include both a zip and the exe.
See also Issue #157

Best wishes,
Andreas W

**Comment by praynaud** [comment]
@gpadd I observed the same thing on my local machine. At least, Windows Security had an option to allow it. McAfee just completely blocked it without any option to allow it. I had to temporarily disable McAfee in order to download and unzip the file. Once unzipped, the contents were fine.

**Comment by skeeto** [comment]
It's not that it's a self-extracting archive, but that it's not code signed, doesn't have an established reputation (hasn't been observed on millions of systems), and the file has the [Mark of the Web](https://en.wikipedia.org/wiki/Mark_of_the_Web) (from being downloaded via browser). Unfortunately each factor is out of my control, so if you download it the conventional way you have to deal with the conventional hassles. See also #154.

**Comment by xparq** [comment]
BTW, what was wrong with the .zip files? Or, what's so compelling with the .exe packs?

Self-extracting executables have always been a net negative for me. Especially now that Windows is so trigger-happy (which I don't really mind by itself, better safe than sorry).

**Comment by Peter0x44** [comment]
@xparq all of the reasoning for choosing the sfx is in #87 .
Note that you don't *have* to use the sfx. Right clicking on the exe, then using any of the options in the "7-Zip" sub menu still work fine. The archive is quite literally concatenated to the stub.

The only benefit not mentioned there is that 7-Zip does not proliferate the "mark of the web" in things it was extracts. What that means in practice and if it makes a real effect is still unclear to me.

**Comment by ale5000-git** [comment]
I usually when  download a file select right click => properties; here you can remove directly the "mark of the web".

PS: Also WinRAR can extract 7-Zip sfx archive without to use the sfx.

**Comment by xparq** [comment]
> @xparq all of the reasoning for choosing the sfx is in #87 .

Thanks a lot, that's useful information. (Would've been nice to have it mentioned in the release notes, though; at least this thread could've been spared.)

> Note that you don't _have_ to use the sfx. Right clicking on the exe, then using any of the options in the "7-Zip" sub menu still work fine. The archive is quite literally concatenated to the stub.

Thanks, I know how SFX unpackers work. Two point you've missed here are 

- that there's no "7-Zip sub menu", unless you've installed 7-Zip with the necessary Windows integration. Which those of us who prefer CLI tools and portable apps (exactly the kind w64devkit itself is), don't do. But since I (therefore) never use Explorer and never right-click things there, this is a moot point anyway (because things like FAR Manager can do the same more conveniently).

- OTOH, for those who _are_ on the GUI, _and_ have not yet installed 7-Zip -- i.e. exactly the folks the SFX exe has any benefit at all whatsoever -- are still kinda forced to run it, aren't they?

_(Next up, @Peter0x44, please downvote this comment, too, and lecture me about using the issue search next time more diligently, instead of posting user feedback, that you personally don't like, to the developer.)_

**Comment by Peter0x44** [comment]
> lecture me about using the issue search next time more diligently

I did no such thing, please keep it civil. I was just answering the question. I did not imply you should have searched, or missed anything. There is no "lecture".

> that there's no "7-Zip sub menu", unless you've installed 7-Zip with the necessary Windows integration. Which those of us who prefer CLI tools and portable apps (exactly the kind w64devkit itself is), don't do. But since I (therefore) never use Explorer and never right-click things there, this is a moot point anyway (because things like FAR Manager can do the same more conveniently).

I only brought it up as one example. I use peazip for this purpose, when I want something "portable", 7-zip doesn't seem to support this use case well. I think I mentioned this in a different comment.
https://github.com/skeeto/w64devkit/issues/155#issuecomment-2273463566
This comment also mentions you can use 7zr.exe too, which is command line and does work "portable".

> OTOH, for those who are on the GUI, and have not yet installed 7-Zip -- i.e. exactly the folks the SFX exe has any benefit at all whatsoever -- are still kinda forced to run it, aren't they?

Yes. They are forced to run it.

> BTW, a third point, which I may be wrong about (as I can't remember properly now): the Windows antimalware stuff tends to trigger for some downloaded .exes even without ever attempting to run them. Something I've never had with .zip files.

I'm not sure on this point either. I vaguely recall a time when this did happen to me but I could be wrong. Hopefully this can stop if signing the sfx becomes feasible.

> (Would've been nice to have it mentioned in the release notes, though; at least this thread could've been spared.)

I agree. @skeeto can still edit the release notes, at least to mention renaming to exe to 7z or the other options you have to extract with external programs. I think it would help.

**Comment by matsobdev** [comment]
There is an odd child: bin\debugbreak.exe with 50/50 VT score. I know - debug might be hard to swallow by an antivirus, but some investigation still might be nice.

**Comment by grable0** [comment]
Crap anti-virus doesnt like it when you call debug apis. Its purely matching import names. No investigation needed.

**Comment by skeeto** [comment]
@matsobdev, see #132. The source for `debugbreak.exe` is `src/debugbreak.c` ([also](https://nullprogram.com/blog/2022/07/31/)) The EXE in question is about 90 x64 instructions and, in total, imports 11 functions from `kernel32.dll`. Anyone who can read x64 assembly can validate the binary with a few minutes of work. Of those 11 imports, 5 are used to meddle with other processes (i.e. to call [`DebugBreakProcess`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-debugbreakprocess)). A tiny program with a large impact freaks out virus scanners because malware tends to have that profile.

(Note: While `objdump -dw` can produce a disassembly listing, if you *actually* do not trust a binary then you shouldn't expose it to Binutils. It's [not intended to process untrusted inputs](https://sourceware.org/cgit/binutils-gdb/tree/binutils/SECURITY.txt). In general, w64dk does not include security analysis tools. That's the realm of Radare2, Ghidra, IDA, etc.)
