### ISSUE TITLE
cant extract exe

### ISSUE THREAD

**Issue by yasieb** [skeeto/w64devkit#161]
feature request

can i create portable exe vst  and extract them using w64devkit

**Comment by Peter0x44** [comment]
Why is it that you "cant extract exe"

> can i create portable exe vst and extract them using w64devkit

I'm not sure what this means either.
If Windows defender is getting in the way, then installing 7-zip, peazip, or some other software capable of extracting 7z might work, instead of using the sfx part of the archive itself.

There are some instructions here that could help:
https://github.com/skeeto/w64devkit/issues/155#issuecomment-2273463566

**Comment by skeeto** [comment]
Following on to @Peter0x44's comments, until you can provide details and explain your situation I'm going to close this.
