### ISSUE TITLE
Can you add openssl?

### ISSUE THREAD

**Issue by chatchoi** [skeeto/w64devkit#169]
It should be a plugin (.7z archive), that anyone want to use it need to download and extract into a w64devkit installation manually. Some projects on Github requires OpenSSL libraries.

**Comment by skeeto** [comment]
Sorry, as a rule I do not deliver libraries through w64dk beyond language runtimes. Supporting a library properly is a substantial undertaking, and it's at odds with a static distribution. Every OpenSSL security update would require a w64dk release with an updated OpenSSL. In general, the particular version of an included library will often be the wrong version for some users anyway.

A separate "plugin" as you suggest would solve some of these issues. I don't need to be involved in that, though. (I also personally dislike OpenSSL and would rather deal with it as little as possible.) Anything that unpacks into the standard arch-prefixed directory layout would work. In fact, the official SDL2 "mingw" ZIP already works this way.

OpenSSL has an especially poor build system (Perl?!), practically hostile to Windows. It's a challenge even to obtain pre-built OpenSSL artifacts. If someone were to work out an alternative build script (hint: there is no moral obligation to interact with a project's build system when compiling it) that, given an OpenSSL source tree, works in w64dk out-of-the-box, I could put that in `contrib/` so that it's at least easy to build.

**Comment by Peter0x44** [comment]
> It's a challenge even to obtain pre-built OpenSSL artifacts. 

I recently had to obtain openssl for a project, and I found downloading the mingw64 package from msys2 worked just fine.

You can find the link on this page:
https://packages.msys2.org/packages/mingw-w64-x86_64-openssl
`File: https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-openssl-3.5.4-1-any.pkg.tar.zst`
Since it's zstd compressed, you need to put `zstd.exe` on your PATH for tar to work. You can get zstd from here:
https://github.com/facebook/zstd/releases/latest

Likely the same is possible for many other msys2 packages. It's definitely a source worth looking at sometimes, for dependencies with tricky build systems.
