### ISSUE TITLE
Virus reported in vimrun.exe by Avira Anti-Virus?

### ISSUE THREAD

**Issue by 3Delights** [skeeto/w64devkit#172]
Avira Reports that vimrun.exe in w64devkit.exe downloaded from here ( 2.0.0 w64devkit-x64-2.0.0.exe ) contain a virus HEUR/ACP.

False positive?

**Comment by 3Delights** [comment]
When running w64devkit Avira goes on to flag several files as harmful and quarantines them.

**Comment by skeeto** [comment]
Yes, that's a false positive. As with many of these false positives it's 
trivially harmless at that. The EXE is ~30KB, ~100 lines of code helper 
program that does nothing except call _wsystem(). You'll need to add the 
directory as an exclusion or otherwise bypass/disable your virus scanner. 
It's likely to flag your own programs as malware, too, so you'll need the 
same exclusion for whatever directory you're working in, too.
