### ISSUE TITLE
Version 2.0.0's busybox doesn't run atom.sh

### ISSUE THREAD

**Issue by enadream** [skeeto/w64devkit#189]
I use the Atom editor to code. I often use W64DevKit with it. After updating W64DevKit to the latest release (2.0.0), I started getting an error message when typing 'atom .' that indicated I forgot to use 'fi' in the 'atom.sh' file. However, this was not the case. After some investigation, I discovered that the problem was with busybox.exe. Replacing busybox.exe to w64devkit v1.23.0's Busybox resolved the issue.

**Comment by enadream** [comment]
Here is the atom.sh file if it's needed. It gives error at line 6, says you need to use 'fi' before '('

`#!/bin/bash
# Get current path in Windows format
if command -v "cygpath" > /dev/null; then
  # We have cygpath to do the conversion
  ATOMCMD=$(cygpath "$(dirname "$0")/atom.cmd" -a -w)
  ARGS=( $(cygpath -a -w "$@" | tr '\n' ' ') ) 
else
  ARGS=$@
  pushd "$(dirname "$0")" > /dev/null
  if [[ $(uname -r) =~ (M|m)icrosoft ]]; then
    # We are in Windows Subsystem for Linux, map /mnt/drive
    root="/mnt/"
    # If different root mount point defined in /etc/wsl.conf, use that instead
    eval $(grep "^root" /etc/wsl.conf | sed -e "s/ //g")
    root="$(echo $root | sed 's|/|\\/|g')"
    ATOMCMD="$(echo $PWD | sed 's/\/mnt\/\([a-z]*\)\(.*\)/\1:\2/')/atom.cmd"
  else
    # We don't have cygpath or WSL so try pwd -W
    ATOMCMD="$(pwd -W)/atom.cmd"
  fi
  popd > /dev/null
fi

if [ "$(uname -o)" == "Msys" ] || [[ $(uname -r) == *-Microsoft ]]; then
  cmd.exe //C "$ATOMCMD" "$@" # Msys amd WSL think /C is a Windows path...
else
  cmd.exe /C "$ATOMCMD" "${ARGS[@]}" # Cygwin does not
fi
`

**Comment by skeeto** [comment]
The bash shebang suggests this was never intended to work, and so what did 
work was a happy accident. While w64devkit does not have bash (bash.exe is 
an alias for ash), busybox ash supports some bash features. That doesn't 
include arrays, which is the syntax issue on line 6. I'm surprised this 
script ever worked in the first place.

If it works in 1.23.0 but not 2.0.0 then something changed in busybox-w32 
between FRP-5301-gda71f7c57 and FRP-5398-g89ae34445. However, when I tried 
1.23.0, and with a direct FRP-5301 build, I got the same syntax error.

(Initially I suspected the //C, for which busybox-w32 ash itself already 
has a built-in workaround (#50). However, it doesn't fit the pattern, and 
besides, wouldn't affect the earlier parsing issue.)

**Comment by enadream** [comment]
Okay, you are right. The old version of busybox uses atom.cmd file instead of atom.sh file. I checked this using "which atom" command. The new version (FRP-5398) returns atom.sh but the old version (FRP-5301) returns atom.cmd. So new version tries to run sh file instead of cmd.

**Comment by rmyorston** [comment]
@enadream I'm not sure what's going on here. The way extensions are handled when looking for a command to execute has changed over time. There _was_ a change between FRP-5301 and FRP-5398, but it didn't affect the preference for `.sh` over `.cmd`. That's been constant since support for `.sh` was added in 2018. I don't understand why your FRP-5301 executes `atom.cmd`.

I've installed atom on Windows 10 using the 1.60.0 installer AtomSetup-x64.exe from the [releases](https://github.com/atom/atom/releases) on GitHub. I can see that `atom.sh` and `atom.cmd` exist, though the installer didn't add their directory to `PATH`. If I add it by hand both FRP-5301 and FRP-5398 pick up `atom.sh` when asked to execute `atom`.

How did you install atom?

**Comment by enadream** [comment]
@rmyorston I installed atom from here [AtomSetup-x64.exe](https://github.com/atom/atom/releases/download/v1.60.0/AtomSetup-x64.exe) . I think I didn't add the Atom variable to the Windows environment variables. Here are the path variables and Atom's path
![atom path variable](https://github.com/user-attachments/assets/b056ecfe-a246-4ede-8214-093020a70dbf)
![commands](https://github.com/user-attachments/assets/b92b098a-7812-4447-a533-e7159d40d0f3)

**Comment by enadream** [comment]
@rmyorston the atom/bin/ folder contains these files. As far as I understand busybox FRP-5301 selects atom.cmd, FRP-5398 selects atom file.

![folder](https://github.com/user-attachments/assets/8500d9bc-ef88-42a8-8ba0-25e4f0742e69)

**Comment by enadream** [comment]
I tested on my second computer, I freshly installed atom from the link I sent above and I downloaded https://github.com/skeeto/w64devkit/releases/download/v2.0.0/w64devkit-x64-2.0.0.exe and https://github.com/skeeto/w64devkit/releases/download/v1.23.0/w64devkit-1.23.0.zip the results are same. Version w64devkit V2.0.0 uses "atom", w64devkit v1.23.0 uses "atom.cmd" .

**Comment by rmyorston** [comment]
OK, I was confused by the reference to `atom.sh`. That file _isn't_ in the `bin` directory, rather it's run by the `atom` script which _is_ in the `bin`directory.

I made a new Windows 10 VM and installed atom again. This time it did add the `bin` directory containing the `atom` and `atom.cmd` files to `PATH`.

The thing that _did_ change between FRP-5301 and FRP-5398 is how executable files without an extension are handled. They now consistently take precedence over a file with an executable extension. So with recent versions of busybox-w32 the `atom` shell script is run, not the `atom.cmd` batch file as before. I think this behaviour is more consistent with how things work on Unix.

If you don't need to use the `atom` script you could rename it to `atom.bak` or such. Otherwise you could make `atom` an alias for `atom.cmd` by putting the following in ~/.profile:
```sh
alias atom=atom.cmd
```
I daresay there are other workarounds too.

**Comment by enadream** [comment]
@rmyorston I changed atom to atom.bak and problem solved. Thanks.

**Comment by skeeto** [comment]
Thanks for looking into this, Ron!
