### ISSUE TITLE
Include YASM + FLEX + BISON + BYACC?

### ISSUE THREAD

**Issue by 3oheicrw** [skeeto/w64devkit#27]
These small tools are very useful (when they are needed). Including them in the distro helped us not having to spawn a full MSYS2 shell.

**Comment by skeeto** [comment]
I looked into flex and Bison earlier this year. However, flex depends on 
POSIX features, which I'd have to supply somehow. Since it's not important 
to me, I didn't want to spend (probably substantial) time. If it were as 
simple as "--host=x86_64-w64-mingw32", "make -f mingw.mak", or "cc *.c" 
then I would probably include these two tools.

Like NASM, Yasm is well-behaved and trivial to cross-compile, making it a 
solid fit for w64devkit. I would only include the three tools, not the 
library. If I had a preference for Yasm, it would probably have been 
included instead. However, I'm not currently interested in including 
another redundant assembler. Counting GAS, there are already two. If 
anything, I would replace NASM with Yasm.
