### ISSUE TITLE
Include the mintty shell and add the setting to use it as the default shell?

### ISSUE THREAD

**Issue by 3oheicrw** [skeeto/w64devkit#28]
Something in w64devkit.ini (disabled by default) that could be turned on the use the included mintty shell by default? The Windows Command Prompt shell sucks IMO.

**Comment by skeeto** [comment]
I'll start with my philosophy: w64devkit is an offline, lightweight, 
self-contained, complete, native development kit for building native 
Windows software. The two uses of "native" are key in this case. The kit 
itself is 100% native Windows software, for better or worse. There is no 
virtual filesystem or POSIX emulation (beyond what Windows itself 
provides). In contrast, Cygwin and MSYS2 are platforms on top of Windows 
and the software running on these platforms is not native. This isn't a 
bad thing, and it has its uses, but the goals are different.

The target is also native Windows. That means when developing a console 
application using w64devkit, the target system is expected to be running a 
stock console, whatever form that currently takes. In that sense, it's 
useful to be working and, more importantly, testing on top of that stock 
console since it's the target. This is fundamental to w64devkit even 
beyond the console: no pretending the system is something other than it 
is, and instead tackling Windows on its own terms. If you're used to other 
operating systems this may seem difficult or pointless, but this is a 
distinct skill and the situation isn't so bad once you learn it. I didn't 
appreciate it myself until I started watching Handmade Hero.

Mintty is out-of-bounds since it's not native Windows software. It runs on 
the Cygwin/MSYS2 platform, so like with Git on Windows, I'd have to 
include/embed a MSYS2 installation just to run this terminal. That's 
adverse to my goals. If you install it separately, you can launch 
w64devkit within Mintty. It's surprisingly easy to set up a shortcut to do 
so. Though because it's a different platform it doesn't work well. Even 
cmd.exe doesn't work correctly inside Mintty, so this whole idea seems 
pretty hopeless.

An alternative native console like ConEmu is a much better fit, and I've 
(very casually) considered including such a console even if I have to 
write it myself. You can run w64devkit inside it, and it works pretty well 
except for some issues with escape handling. (Is this a busybox-w32 issue 
or a ConEmu issue? My current guess is the latter.) It's certainly better 
than the Windows 7 console, but its performance is noticeably worse than 
the Windows 10+ console, at least on my system, so I don't see any 
advantages beyond tabs.

Unfortunately configuring a console from w64devkit.ini is backwards. Since 
w64devkit.exe is a console application, it gets a console before it reads 
the INI. It would need to launch another instance of itself with that 
initial console flashing in and out of existence. It's really more the job 
of the console/terminal software to launch w64devkit.exe as a shell, so 
this is really a console/terminal configuration.

Besides this, as of Windows 10 the console is really quite serviceable and 
capable. I use it regularly (via w64devkit) and have no more trouble with 
it than any typical terminal emulator. (I have yet to find a terminal 
emulator on Linux I'd qualify as "perfect.") As you said, it's the shell, 
cmd.exe, that's abysmal, but w64devkit already replaces it with the 
superior busybox-w32 shell, which is one of the main features.

w64devkit also works surprisingly well with Windows Terminal, and you can 
configure a profile to use w64devkit.exe as the shell. That makes much 
more sense than attempting the same via w64devkit.ini.

**Comment by avih** [comment]
> An alternative native console like ConEmu is a much better fit

While conemu is indeed quite capable, on Windows 10 or 11 the Windows terminal (not console) is a fairly useful and quite configurable terminal with enough xterm features and much nicer to work with than the windows console. I'm guessing mintty is probably with slightly more features, but the windows terminal might be enough (or more) for most tasks. YMMV.

I believe it now comes with Windows 11, but is available also for win10, and works very nicely with busybox-w32 (which uses the containing terminal VTXXX escapes support when available by skipping the internal "ansi emulation", though this also works with windows console on Widnows 10).

Stable and nightly builds are [Availble here ](https://github.com/microsoft/terminal/releases)

**Comment by ruanjiasing** [comment]
> > An alternative native console like ConEmu is a much better fit
> 
> While conemu is indeed quite capable, on Windows 10 or 11 the Windows terminal (not console) is a fairly useful and quite configurable terminal with enough xterm features and much nicer to work with than the windows console. I'm guessing mintty is probably with slightly more features, but the windows terminal might be enough (or more) for most tasks. YMMV.
> 
> I believe it now comes with Windows 11, but is available also for win10, and works very nicely with busybox-w32 (which uses the containing terminal VTXXX escapes support when available by skipping the internal "ansi emulation", though this also works with windows console on Widnows 10).
> 
> Stable and nightly builds are [Availble here ](https://github.com/microsoft/terminal/releases)

And you don't care about older Windows versions?

**Comment by avih** [comment]
> And you don't care about older Windows versions?

I care very much, but I don't control which windows versions are supported by the Windows Terminal. Therefore on older windows versions this suggestion is not relevant.

Either way, Mintty is only a terminal, lke xterm, There's no such thing as "Mintty shell". The shell which runs inside mintty is usually bash from the environment which MIntty was bundled with (cygwin, msys2, git for windows, WSL).

Mintty doesn't support, as far as I know, replacing the Windows console in a native windows environment. The windows console would work, or ConEmu could help.

The shell which runs in w64devkit is from busybox-w32, it's called ash, and it's similar, but with less features than bash.

I don't know whether there are versions of bash for native windows which can be used instead of ash with w64devkit. I do know that there's bash from msys (1, not 2), but msys1 is not a pure native windows env - its a "light fork" of old cygwin (1.3), but it might be enogh for you if you can set it up. There might be other versions of pure windows native bash our there, but I think not recent.
