### ISSUE TITLE
workaround to make ctrl+z work?

### ISSUE THREAD

**Issue by hsnyder** [skeeto/w64devkit#30]
At least on my machine, using the default command prompt terminal, Ctrl-Z to suspend VIM also seems to suspend the shell, dropping me back into the windows command prompt. Do you experience this same behavior and if so, do you know of a workaround?

**Comment by skeeto** [comment]
There is no job control on Windows, so Vim cannot actually suspend itself 
as it does on unix-like platforms. Instead it simulates a suspend by 
starting a new shell. (See "help :stop" in Vim.) You're not going "back 
into the windows command prompt" but *forward* into a new command prompt 
spawned by Vim itself. By default Vim uses cmd.exe as its shell, and I 
even make deliberate effort to arrange for this (see 916e5ac). Exit this 
shell when you're done to return to Vim.

You can set Vim to use the busybox-w32 shell, which is what I do myself 
despite the consequences. Be warned that native Windows Vim does not work 
reliably with anything except cmd.exe. Vim uses the C system() function to 
launch subprocesses, which goes through cmd.exe no matter what shell you 
set in Vim. On all platforms, you end up with two layers of shells any 
time you run a command due to the use of system(). In w64devkit, if you 
set the shell to sh.exe, then run a command, it will launch cmd.exe to 
launch sh.exe, then sh.exe runs your command. The main issue is that Vim's 
shell quoting facilities cannot nest POSIX shell quoting inside cmd.exe 
quoting, so it breaks under any command requiring non-trivial quoting.

Now that you've been properly warned, here's my shell configuration:

set sh=sh shcf=-c sxq=\"

The first option, sh, is sufficient to get a non-login w64devkit shell 
when you CTRL-z. The others let you run simple commands (read: commands 
without complex quoting) using this shell. When you CTRL-z there will be a 
cmd.exe interfering with the console so will be an unpleasant shell, and I 
cannot recommend spending much time in it. See here:

Well-behaved alias commands on Windows
https://nullprogram.com/blog/2021/02/08/

If you're curious what Vim could be doing better instead of system(), see 
my article below, specifically the part combining "cmdline_from_argv8" 
with CreateProcessW. It's analogous to fork+exec instead of system(). This 
would get cmd.exe completely out of the loop.

The wild west of Windows command line parsing
https://nullprogram.com/blog/2022/02/18/

That's what it would take for good CTRL-z behavior in w64devkit. Were it 
as simple as setting those Vim variables, I would have patched it as the 
default already.

**Comment by hsnyder** [comment]
_Very_ interesting, Chris. Thank you! It sounds to me like developing an alternative workflow is going to be a wiser and more profitable route than trying to fix this.
