### ISSUE TITLE
Add a LLVM MINGW based w64devkit version

### ISSUE THREAD

**Issue by 2cls0f** [skeeto/w64devkit#44]
Unlike the Clang on this proposal: https://github.com/skeeto/w64devkit/issues/43 this Clang is entirely LLVM based and only uses LLVM tools and LLVM's libcxx, libcxxabi,... No GCC parts is needed. Inspired from this: https://github.com/mstorsjo/llvm-mingw

This will be an entirely new and separate w64devkit version that distinct from the normal GCC based w64devkit.

**Comment by skeeto** [comment]
I don't object to the idea, but since I also don't really have a use for 
it, I'm unlikely to put the time into building and maintaining something 
like this. However, if you're interested, I encourage you to give it a 
shot yourself. You can use w64devkit as a kind of foundation to get you 
started.
