### ISSUE TITLE
`test -e` fails on (healthy) symlink

### ISSUE THREAD

**Issue by xparq** [skeeto/w64devkit#46]
$ pwd
    C:/sz/prj/Args/test

    $ busybox test -e tmp/symlink && echo ok
    ok
    $ test -e tmp/sylink && echo ok

:-o

    $ which busybox
    C:/SW/devel/tool/w64devkit/w64devkit-32/bin/busybox.exe
    $ which test
    test

But wait, there's more:

    $ cd tmp && test -e symlink && echo ok
    ok

:-oo

    $ readlink symlink
    C:/sz/prj/Args/test/tmp/README.out
    $ test -f README.out && echo ok
    ok

Any idea, what can cause this?

**Comment by rmyorston** [comment]
>Any idea, what can cause this?

I thought so, but it doesn't match your report.

There was a bug in the last [commit](https://github.com/rmyorston/busybox-w32/commit/31467ddfcbbc433ed9ceff2eae2a359d0ca1e6d5) before the FRP-4716 release (which is the version used in w64devkit 1.17.0). It was later [fixed](https://github.com/rmyorston/busybox-w32/commit/1b3002fb63f83498d210cfb1cc189313df0eb8c5). But that related to relative symlinks, an absolute symlink should be OK.

I can reproduce your problem in w64devkit if the symlink is relative but not if it's absolute.

**Comment by xparq** [comment]
Roy, yep, an abs. link was the first thing to try upon encountering this. :) I'm gonna have a closer look when I can.

But, out of the 3 mysteries here, the first one (a "mystery" only 'coz I'm new to w64devkit): am I correct that the BB sh does the right thing here, and the (whatever other?) shell in charge of that "just `test`" seems inferior (despite being "other than BB" should imply it's a more robust choice, BTW)? Anyway, do I really see two distinct `sh` implementations in action here? Or both are just BB, but in different modes of operation? Thanks!

**Comment by skeeto** [comment]
I'm also unable to reproduce the issue for absolute symlinks. I tested in 
an isolated "home=." w64devkit.ini config run as administrator (instead of 
changing the overall system configuration regarding symlinks):

# mkdir tmp
# echo hello >tmp/README.out
# ln -s "$PWD/tmp/README.out" tmp/symlink
# test -e tmp/symlink && echo ok
ok
# busybox test -e tmp/symlink && echo ok
ok

Unless you've added another one, there should only be one shell, busybox 
ash, on your path and when you invoke "test" I believe busybox ash prefers 
its built-in test versus the "test.exe" alias I put in bin/, which agrees 
with your "which" output. (You could delete or move it as another test.) 
When you use "busybox test" I believe it's starting another process.

Since it's now possible to build busybox in w64devkit, you could compile a 
debug build, open it in w64devkit's own GDB, set a breakpoint in the test 
app, start sh, run your test, then step through "test -e". This was to be 
my own next step if I could reproduce. I recommend "set new-console" so 
that the shell runs in its own console window, leaving the original 
console to GDB. If you want to regain control in GDB without killing the 
shell process, run w64devkit's "debugbreak" command from anywhere, even 
the debuggee.

**Comment by xparq** [comment]
Thank you, guys. At the moment I'm unable to reproduce it too... :-o

**Comment by xparq** [comment]
Hmm... Note that I'm intentionally running the 32-bit flavor of the w64devkit packages (1.17.0), mainly to see if it would work fine as a common-ground choice, regardless of the actual host bit length.

Am I correct to assume that it should?

**Comment by xparq** [comment]
_(Jesus, just deleted yet another confused/confusing comment, sorry!... :) )_

**Comment by xparq** [comment]
I'm closing this "tentatively", as nobody else seems to have had anything similar apparently, and even I don't have it any more... And if feels so bad to have this crosshair on your nice project. :)
