### ISSUE TITLE
Final Zip File Cannot unzip Error

### ISSUE THREAD

**Issue by cuongnguyengit** [skeeto/w64devkit#69]
![image](https://github.com/skeeto/w64devkit/assets/45245565/4293025f-29b2-4adb-90bc-0f3e669bbef3)

anyone help me, plz?

**Comment by skeeto** [comment]
Can you share the exact steps you used to build this? That .zip is about 
twice as large as it should be. With "hd w64devkit.zip | head" the first 
two bytes should be "PK".

**Comment by cuongnguyengit** [comment]
I set up follow your direction
git clone https://github.com/skeeto/w64devkit.git
cd w64devkit
docker build -t w64devkit .
docker run --rm w64devkit >w64devkit.zip

**Comment by skeeto** [comment]
I thought more about the 2x detail and realized what's happening: You're 
using PowerShell, right? "No way could it screw up something as basic as 
file redirection," I thought, yet I tried it myself and can exactly 
reproduce your issue. This is typical PowerShell brain damage where 
"redirect to a file" actually means "redirect through PowerShell" which 
then "helpfully" translates your data into UTF-16, a format nobody wants 
nor uses for text files. That, of course, increases the size by 2x — a 
familiar outcome. This is not my first rodeo.

The solution: Use either cmd.exe or w64devkit itself. PowerShell is an 
embarrassment of a shell, a kind of cruel joke that keeps on going. One 
reason w64devkit exists is that, even still in 2023, Microsoft with their 
trillions of dollars is unable to produce and supply a decent system shell 
that can compete with hobbyists.

**Comment by cuongnguyengit** [comment]
it was really worked in cmd. Thanks for your support.

**Comment by garoto** [comment]
Timelines must have forked around the late 70s or early 80s and we're now living its worst version possible, where MS in-house garbage tech is seem as "standard" and newer generations can't possibly know any better, since the shilling is _too stronk_.

You should write about your thoughts regarding powershell in your website. Would love to see if my non-computer-programmer concepts can/would somewhat align with the ones from a seasoned C programmer at all.
