### ISSUE TITLE
Add `m4` program 

### ISSUE THREAD

**Issue by Tim-Sobolev** [skeeto/w64devkit#78]
I was using `w64devkit` to build [GNU MP](https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz) library recently.

To run `configure` script from `cmd.exe` were created scripts, based on [comment](https://github.com/rmyorston/busybox-w32/issues/297#issuecomment-1445325198). 
Scripts were placed to the `w64devkit\bin` directory:

**prepare.sh**
```
if [[ "$OSTYPE" == "msys" ]]; then
    echo "MSYS..."
else
    export PATH_SEPARATOR=';'
    export ac_executable_extensions='.exe'
fi
export build_alias="$(uname -m)-pc-mingw64"

if [ -f configure ]
then
    echo "Converting configure..."
    sed -i 's/func_convert_file_msys_to_w32/func_convert_file_noop/' configure
    ./configure $@
fi
```

**prepare.cmd**
```
sh %~dp0prepare.sh %*
```

However, I have to use `m4` from old [unxutils](https://unxutils.sourceforge.net/) project.  
It will be nice to have it available in the standart distribution packege.

**Comment by skeeto** [comment]
I'm not interested in including m4, but some good news: As of w64devkit 2.0.0 you can easily compile m4 from source the usual way yourself:

    $ tar xf m4-1.4.19.tar.xz
    $ cd m4-1.4.19/
    $ ./configure CFLAGS=-fpermissive
    $ make -j$(nproc)

And then you'll have `m4.exe`. There's currently a bug in m4 and `-fpermissive` is required when compiling m4 with GCC 14 or later. You'd need it even outside of w64devkit.

**Comment by Peter0x44** [comment]
I'm not sure this is enough. The resulting m4 seems rather buggy.
I had to configure it with:
`$ ./configure --with-syscmd-shell=sh.exe --prefix=C:/programming/toolchains/w64devkit/`
for it to work for some codebases. And it still seemed to have problems possibly similar to make's with spaces.
And some others I couldn't quite describe...
Older versions worked better.

**Comment by Peter0x44** [comment]
this is with the latest GNU m4 1.4.20. Older versions seem to work better.

**Comment by skeeto** [comment]
Ah, `--with-syscmd-shell` makes sense. Digging into its `configure.ac` I see it picks `cmd` otherwise, which may not work with m4 scripts that shell out and expect sh. Plus m4 uses unix-style quoting with it regardless. I see 1.4.20 has a change to keep `cmd` working as intended, so they're trying to keep it working. What made `--prefix` necessary?

m4 is one of those tools I've thought about re-writing, except that I can't stand the m4 language. I'm confident it could be done with a fraction of the code, without an enormous MLoC dependency, and without the recursive, complex, and slow build. It would be faster, too, by dropping null-terminated strings. I see GNU m4 already uses obstacks, so there's probably not much to gain from an improved allocator in a rewrite. Because GNU m4 is packed with features, it would be quite a lot of work filling out the long tail of features.

**Comment by Peter0x44** [comment]
> What made --prefix necessary?

Otherwise, make install would put it in `C:/usr/bin/m4.exe`

**Comment by skeeto** [comment]
Ah, I thought maybe it was a run-time issue, with m4 needing to know where it would live. In my build example I didn't show `make install` because in the end you have just `m4.exe`, and you can manually copy it wherever is appropriate on your PATH! Except for locale stuff (so maybe add `--disable-nls`), I don't think it needs anything else.
